# Q1

## （1）

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "name": ["Tom", "Jerry", "Mike"],
    "score": [85, 92, 78],
    "gender": ["男", "女", "男"]
})

df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

## （2）

In [2]:
df.head(1)

  name  score gender
0  Tom     85      男

In [3]:
df.shape

(3, 3)

In [4]:
df.columns

Index(['name', 'score', 'gender'], dtype='object')

In [5]:
df.dtypes

name      object
score      int64
gender    object
dtype: object

## （3）

In [6]:
data = [[1, "A"], [2, "B"], [3, "C"]]

df_list = pd.DataFrame(data, columns=["id", "tag"])

df_list

   id tag
0   1   A
1   2   B
2   3   C

# Q2

## （1）

In [7]:
df[["score", "gender"]]

   score gender
0     85      男
1     92      女
2     78      男

## （2）

In [8]:
df.loc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

## （3）

In [9]:
df[df["score"] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

## （4）

In [10]:
df["grade"] = np.where(df["score"] >= 90, "优秀", "良好")

df

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

## （5）

In [11]:
df_drop_gender = df.drop(columns=["gender"])

df_drop_gender

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

# Q3

## （1）

In [12]:
df_missing = pd.DataFrame({
    "x": [1, None, 3],
    "y": [None, 5, 6]
})

df_missing

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [13]:
df_missing.isnull()

       x      y
0  False   True
1   True  False
2  False  False

In [14]:
df_missing.isnull().sum()

x    1
y    1
dtype: int64

## （2）

In [15]:
df_fill = df_missing.fillna(0)

df_fill

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [16]:
df_dropna = df_missing.dropna()

df_dropna

     x    y
2  3.0  6.0

# Q4

## （1）

In [17]:
df.groupby("gender")["score"].agg(["mean", "max"])

        mean  max
gender
女       92.0   92
男       81.5   85

## （2）

In [18]:
df.groupby("gender").size()

gender
女    1
男    2
dtype: int64

# Q5

## （1）

In [19]:
df_sort = df.sort_values(by="score")

df_sort

    name  score gender grade
2   Mike     78      男    良好
0    Tom     85      男    良好
1  Jerry     92      女    优秀

## （2）

In [20]:
df_repeat = pd.DataFrame({
    "name": ["Tom"],
    "score": [85],
    "gender": ["男"],
    "grade": ["良好"]
})

df_with_repeat = pd.concat([df, df_repeat], ignore_index=True)

df_with_repeat

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男    良好

In [21]:
df_unique = df_with_repeat.drop_duplicates()

df_unique

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

# Q6

## （1）

In [22]:
df1 = pd.DataFrame({
    "id": [1, 2],
    "name": ["X", "Y"]
})

df2 = pd.DataFrame({
    "id": [1, 2],
    "age": [20, 30]
})

df_merge = pd.merge(df1, df2, on="id")

df_merge

   id name  age
0   1    X   20
1   2    Y   30

## （2）

In [23]:
df_a = pd.DataFrame({
    "val": [1, 2]
})

df_b = pd.DataFrame({
    "val": [3, 4]
})

df_concat = pd.concat([df_a, df_b], ignore_index=True)

df_concat

   val
0    1
1    2
2    3
3    4

# Q7

## （1）

In [24]:
df_time = pd.DataFrame({
    "date": ["2025-01-01", "2025-01-02", "2025-01-03"]
})

df_time["date"] = pd.to_datetime(df_time["date"])

df_time

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

## （2）

In [25]:
df_time["month"] = df_time["date"].dt.month
df_time["weekday"] = df_time["date"].dt.dayofweek

df_time

        date  month  weekday
0 2025-01-01      1        2
1 2025-01-02      1        3
2 2025-01-03      1        4

# Q8

## （1）

In [26]:
df["score_standardized"] = (df["score"] - df["score"].mean()) / df["score"].std()

df

    name  score gender grade  score_standardized
0    Tom     85      男    良好                 0.0
1  Jerry     92      女    优秀                 1.0
2   Mike     78      男    良好                -1.0

## （2）

In [27]:
pivot_table = pd.pivot_table(
    df,
    index="gender",
    values="score",
    aggfunc="median"
)

pivot_table

        score
gender
女        92.0
男        81.5